# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: pommitlint

before:
  hooks:
    - go mod tidy

builds:
  - id: pommitlint
    main: .
    binary: pommitlint
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/shuymn/pommitlint/internal/version.Version={{ .Version }}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - THIRD_PARTY_NOTICES.md
      - third_party_licenses/*

checksum:
  name_template: checksums.txt

changelog:
  disable: true

release:
  draft: true
