name: GitHub Actions Lint

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**

jobs:
  lint:
    permissions:
      contents: read
    uses: shuymn/github-actions/.github/workflows/gha.yml@e036bfdd64547031bff7e3a3b21c6596942799eb