name: Renovate

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yml
      - .github/renovate.json
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yml
      - .github/renovate.json

jobs:
  validate:
    permissions:
      contents: read
    uses: shuymn/github-actions/.github/workflows/renovate.yml@eead2bf6ec64083e01cb2fb7b5f8239e48e372a9