name: Renovate

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yml
      - .github/renovate.json
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yml
      - .github/renovate.json

jobs:
  validate:
    permissions:
      contents: read
    uses: shuymn/github-actions/.github/workflows/renovate.yml@65cae648d29f14837e0fbce3dcdbd13a52d101c0