name: Security

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    permissions:
      contents: read
      pull-requests: write
    uses: shuymn/github-actions/.github/workflows/security.yml@e132f66656c12d51632b862d08d7e640e788c51f