name: Security

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    permissions:
      contents: read
      pull-requests: write
    uses: shuymn/github-actions/.github/workflows/security.yml@e036bfdd64547031bff7e3a3b21c6596942799eb