name: Security

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    permissions:
      contents: read
      pull-requests: write
    uses: shuymn/github-actions/.github/workflows/security.yml@e9c395bde26f38d37bd403dc7064e22332bbef78